### ISSUE TITLE
Artemis not detecting Logitech Gaming Software version 8.83.85

### ISSUE THREAD

**Issue by RoboKun** [SpoinkyNL/Artemis#115]
Artemis doesn't even seem to recognize that it's installed, as the detected version is 0.0.0

Error
![ss 2016-06-21 at 08 29 50](https://cloud.githubusercontent.com/assets/10700125/16250868/09156158-37ef-11e6-93e0-098306d5999f.png)
Installed version
![ss 2016-06-21 at 08 31 15](https://cloud.githubusercontent.com/assets/10700125/16250885/32b922e2-37ef-11e6-934f-cb6b9be173f8.png)

**Comment by SpoinkyNL** [comment]
Hey, could you try closing Artemis and anything else that might use your keyboards lighting (Like GTA or The Division) and uninstalling Logitech Gaming Software. After that reinstall it and try lauching Artemis then.

**Comment by RoboKun** [comment]
Have tried Reinstalling LGS as well as disabling Per Profile backlighting with neither resolving the issue. Is there a way to enable logging or something similar?

**Comment by SpoinkyNL** [comment]
Hey, there are some logging features you can enable under settings in the latest pre-release but sadly the Logitech SDK offers no feedback whatsoever, except for this version number (which is clearly not always accurate either).

Just to be sure, are you using the x64 version of the drivers? Also under settings "Allow games to control illumination" should be checked.

**Comment by Thoth2020** [comment]
I use this same firmware version and I don't have issues, so it's not this specific FW.

**Comment by jdubnz** [comment]
Having the same issue. Artemis is detecting LGS 8.75, when I have 8.87.116. As such it can't recognize my G810 keyboard

**Comment by SpoinkyNL** [comment]
Hello,

Could you try shutting down Artemis and any game that might support the
G810 (such as GTA V), uninstalling LGS and reinstalling it again?

Op 11 okt. 2016 23:55 schreef "jdubnz" <notifications@github.com>:

**Comment by jdubnz** [comment]
I tried doing that previously a couple months back, when LGS was actually 8.75. Uninstalled Artemis and updated LGS to what it is now. and tried again but no luck.

I have another keyboard profile app (Aurora) but had it closed when attempting Artemis (for Witcher 3!). No games were running that use Logitech SDK (or any at games at all).

**Comment by SpoinkyNL** [comment]
Hey again, sorry for the delay.

Could you both try uninstalling LGS and making sure it's folder is gone too? This issue arises from the DLL not being removed properly, so getting rid of the entire folder should fix it

It should be in 
`C:\Program Files\Logitech Gaming Software`

If you had the 32-bits version it'll be in
`C:\Program Files (x86)\Logitech Gaming Software`

If you had the 32-bits version that might also be the source of the issue, make absolutely sure you get the 64-bits version. Let me know how it goes! :)

**Comment by SpoinkyNL** [comment]
Hey, does this still occur with the latest version?

**Comment by jdubnz** [comment]
I just redownloaded Artemis after getting the email. This still happens for me. It is still detecting LGS 8.75.30 when I have 8.87.116. Although I never got round to completely deleting and reinstalling LGS sorry

**Comment by jdubnz** [comment]
After a fresh install of LGS it worked. Cheers
