### ISSUE TITLE
Error - Corsair Strafe RGB (RL support broken)

### ISSUE THREAD

**Issue by DKAY15** [SpoinkyNL/Artemis#217]
error: 'Couldn't connect to your corsair keyboard.  Please check your cables/drivers'... etc..

Corsair Strafe RGB, Cue is installed and CUE is functional with Enable SDK checked, however i get the above error message when attempting to use artemis.

any ideas?

**Comment by SpoinkyNL** [comment]
Hey, is this happening since the new update? And have you tried rebooting?

If rebooting doesn't help could you set logging to debug and try enabling
the keyboard, then head to documents > Artemis > logs and drag the newest
log file into the GitHub comment box

Op 13 dec. 2016 21:15 schreef "DKAY15" <notifications@github.com>:

**Comment by DKAY15** [comment]
Sorry, This is actually my first time trying to use Artemis at all so the issue issue could be on my end. 

Am i missing a needed step to enable my Strafe RGB for use with artemis?

Thanks again

Debug:
2016-12-13 16:03:27.0500|FATAL|Artemis.Utilities.Logging|INFO: Set log level to Debug 
2016-12-13 16:03:27.0500|WARN|Artemis.Managers.DeviceManager|Failed enabling keyboard: Corsair RGB Keyboards 
2016-12-13 16:03:27.1918|DEBUG|Artemis.Managers.LoopManager|Cancel LoopManager start, no keyboard

**Comment by SpoinkyNL** [comment]
Oh ok no probs, I just released a new version so I thought it might be caused by that.

Could you try installing [Visual Studio C++ Redistibutable 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145) be sure to grab the x64 version  
And  [Visual C++ Redistributable for Visual Studio 2012 Update 4 - 64 bit](https://www.microsoft.com/en-au/download/confirmation.aspx?id=30679) as well

**Comment by DKAY15** [comment]
Hmm, I installed both 2015 and 2012 and then restarted my pc.. Unfortunately I'm still receiving errors when attmping to enable the keyboard in Artemis

**Comment by SpoinkyNL** [comment]
Ah that's unfortunate :c Could you tell me what version of CUE you're using?

**Comment by DKAY15** [comment]
CUE Version: 2.7.78

**Comment by SpoinkyNL** [comment]
I was running an older version but upgrading to that one didn't give me any trouble. Could you try running this [SimpleDevTest.zip](https://github.com/SpoinkyNL/Artemis/files/650382/SimpleDevTest.zip)?

It's a standable test of the CUE SDK and it should turn your keyboard green/blue-ish

**Comment by DKAY15** [comment]
The simple test runs for me, I get the Green Blue lights kind of waving right to left

**Comment by SpoinkyNL** [comment]
Ok that's a bit strange, Artemis practically uses the same code as that test.

Could you run [this](https://github.com/SpoinkyNL/Artemis/files/650421/SimpleDevTest.zip) version and see if it outputs the following:
```
Press any key to exit ...

Keyboard SDK available: True
Initialized with x64-SDK
Keyboard model: STRAFE RGB
```

Maybe the checks Artemis runs before enabling are returning a false-positive somehow 🤔

**Comment by DKAY15** [comment]
So when I run that test I get the following:

Keyboard SDK available: True
Initialized with x64-SDK

however there is nothing on the third line referencing a keyboard model as you referenced above

**Comment by SpoinkyNL** [comment]
I updated the link after I made the post, if you happened to click it from your mailbox it was the outdated link, my bad. If you could try with the updated link I'll try to figure out what's happening tomorrow (it's past midnight where I'm from :c) 

Thanks!

**Comment by DKAY15** [comment]
Okay, Now I am seeing the correct information via your test:

Press any key to exit ...

Keyboard SDK available: True
Initialized with x64-SDK
Keyboard model: STRAFE RGB


Really strange, I still cannot connect using Artimus. 

thanks again!

**Comment by SpoinkyNL** [comment]
Hey, a few issues popped up with other users and different keyboards as well. I made a mistake compiling the latest update, could you try [this version](https://github.com/SpoinkyNL/Artemis/releases/download/1.6.0.1/Setup.exe)?

**Comment by DKAY15** [comment]
Hey, 

I really do want to stress how much I appreciate your time and patience with me on this.  Your fix does allow my keyboard to be enabled, however the effects do not seem to be functional in game.  For example, If i launch Artemis and enable the rocket league profile nothing happens until i open Rocket League, and then my keyboard simply blinks orange repeatedly until I manually turn off Artemis. 

Any ideas on what I may be doing wrong here?

Thanks again

**Comment by SpoinkyNL** [comment]
Hey, sorry for not getting back to you earlier. The latest Rocket League update broke Artemis's support. The other games should work, if not, let me know

**Comment by Mrwebente** [comment]
Does this mean There won't be any rocket league support in the future, or is this just temporary?
Because any time i start the game all the keyboard does is blinkin red.

**Comment by SpoinkyNL** [comment]
Hey, it's something that needs fixing after every Rocket League update but
Ive been a bit low on time. I'll look into it though

Op 31 dec. 2016 1:45 p.m. schreef "Mrwebente" <notifications@github.com>:

Does this mean There won't be any rocket league support in the future, or
is this just temporary?
Because any time i start the game all the keyboard does is blinkin red.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/SpoinkyNL/Artemis/issues/217#issuecomment-269863509>,
or mute the thread

**Comment by SpoinkyNL** [comment]
I've updated Rocket League to work with 1.26 :)

**Comment by Mrwebente** [comment]
Hi, i know this thread is closed but my G910 is now just black when playing rocket league with the current version of artemis 1.7.1.0 and rl 1.26 no hurry though thank you for your work on this issue!

**Comment by SpoinkyNL** [comment]
Hey, that's odd. Not home right now so can't check but could you set logging to Trace, start an exhibition match drive around for a few seconds.

Then set logging back to info and post the log file, that way I can hopefully see what's happening, thanks!

**Comment by DKAY15** [comment]
Hey Spoinky, 

I'm  experiencing the same issue with my Corsair Strafe. Weirdly enough when i run the log it is reading Counterstrike even though i am Playing rocket league...

2017-01-02 19:55:54.8796|FATAL|Artemis.Utilities.Logging|-------------------------------- 
2017-01-02 19:55:54.8796|FATAL|Artemis.Utilities.Logging|  INFO: Set log level to Trace   
2017-01-02 19:55:54.8796|FATAL|Artemis.Utilities.Logging|-------------------------------- 
2017-01-02 19:55:57.4200|DEBUG|Artemis.DAL.ProfileProvider|Saved profile corsair-strafe-rgb/CounterStrike/Default 
2017-01-02 19:56:02.4422|DEBUG|Artemis.DAL.ProfileProvider|Saved profile corsair-strafe-rgb/CounterStrike/Default 
2017-01-02 19:56:07.4318|DEBUG|Artemis.DAL.ProfileProvider|Saved profile corsair-strafe-rgb/CounterStrike/Default 
2017-01-02 19:56:12.4209|DEBUG|Artemis.DAL.ProfileProvider|Saved profile corsair-strafe-rgb/CounterStrike/Default 
2017-01-02 19:56:17.4297|DEBUG|Artemis.DAL.ProfileProvider|Saved profile corsair-strafe-rgb/CounterStrike/Default 
2017-01-02 19:56:22.4087|DEBUG|Artemis.DAL.ProfileProvider|Saved profile corsair-strafe-rgb/CounterStrike/Default 
2017-01-02 19:56:27.4125|DEBUG|Artemis.DAL.ProfileProvider|Saved profile corsair-strafe-rgb/CounterStrike/Default 
2017-01-02 19:56:32.4262|DEBUG|Artemis.DAL.ProfileProvider|Saved profile corsair-strafe-rgb/CounterStrike/Default 
2017-01-02 19:56:37.4240|DEBUG|Artemis.DAL.ProfileProvider|Saved profile corsair-strafe-rgb/CounterStrike/Default 
2017-01-02 19:56:42.4672|DEBUG|Artemis.DAL.ProfileProvider|Saved profile corsair-strafe-rgb/CounterStrike/Default 
2017-01-02 19:56:47.4477|DEBUG|Artemis.DAL.ProfileProvider|Saved profile corsair-strafe-rgb/CounterStrike/Default 
2017-01-02 19:56:52.4496|DEBUG|Artemis.DAL.ProfileProvider|Saved profile corsair-strafe-rgb/CounterStrike/Default 
2017-01-02 19:56:57.4492|DEBUG|Artemis.DAL.ProfileProvider|Saved profile corsair-strafe-rgb/CounterStrike/Default 
2017-01-02 19:57:02.4576|DEBUG|Artemis.DAL.ProfileProvider|Saved profile corsair-strafe-rgb/CounterStrike/Default 
2017-01-02 19:57:07.4572|DEBUG|Artemis.DAL.ProfileProvider|Saved profile corsair-strafe-rgb/CounterStrike/Default 
2017-01-02 19:57:12.4761|DEBUG|Artemis.DAL.ProfileProvider|Saved profile corsair-strafe-rgb/CounterStrike/Default 
2017-01-02 19:57:17.4866|DEBUG|Artemis.DAL.ProfileProvider|Saved profile corsair-strafe-rgb/CounterStrike/Default 
2017-01-02 19:57:22.4848|DEBUG|Artemis.DAL.ProfileProvider|Saved profile corsair-strafe-rgb/CounterStrike/Default 
2017-01-02 19:57:27.4943|DEBUG|Artemis.DAL.ProfileProvider|Saved profile corsair-strafe-rgb/CounterStrike/Default 
2017-01-02 19:57:32.4968|DEBUG|Artemis.DAL.ProfileProvider|Saved profile corsair-strafe-rgb/CounterStrike/Default 
2017-01-02 19:57:37.4950|DEBUG|Artemis.DAL.ProfileProvider|Saved profile corsair-strafe-rgb/CounterStrike/Default 
2017-01-02 19:57:42.4921|DEBUG|Artemis.DAL.ProfileProvider|Saved profile corsair-strafe-rgb/CounterStrike/Default 
2017-01-02 19:57:47.5096|DEBUG|Artemis.DAL.ProfileProvider|Saved profile corsair-strafe-rgb/CounterStrike/Default 
2017-01-02 19:57:52.5106|DEBUG|Artemis.DAL.ProfileProvider|Saved profile corsair-strafe-rgb/CounterStrike/Default 
2017-01-02 19:57:57.5141|DEBUG|Artemis.DAL.ProfileProvider|Saved profile corsair-strafe-rgb/CounterStrike/Default

**Comment by SpoinkyNL** [comment]
Hey, I believe I've fixed this.

What happened is that I recently reinstalled Windows and thus Rocket League, which defaulted back to my native language, Dutch. This in turn messed up the boost readings, making them only work Rocket League when it was set to Dutch, would've thought, heh.

Let me know if it works well for you guys now :)

**Comment by SpoinkyNL** [comment]
@DKAY15, looks like you still had the profile editor open on the CS:GO page, to avoid any issues make sure you don't leave the editor open when gaming

**Comment by DKAY15** [comment]
Spoinky, this fix worked great!

 I can't thank you enough for taking the time to get this working once again and wanted to let you know it was much appreciated. 

This works awesome

**Comment by SpoinkyNL** [comment]
Cool, glad it works well for everyone. :)
